name: Update gini-index datasets

on:
  # Schedule to run on each 2 month
  schedule:
    - cron: '0 0 1 1,3,5,7,9,11 *'

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Run Makefile
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r scripts/requirements.txt
        make

    - name: Configure Git
      run: |
        git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
        git config --global user.name "${{ env.CI_COMMIT_NAME }}"
      env:
        CI_COMMIT_NAME: "Automated commit"
        CI_COMMIT_EMAIL: "actions@users.noreply.github.com"

    - name: Commit and Push changes
      run: |
        git diff --quiet && echo "No changes to commit" || (
          git add data/ archive/ &&
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}" &&
          git push origin main
        )
      env:
        CI_COMMIT_MESSAGE: "Automated commit"